<?php
/**
 * beminimalist.fr website
 *
 * Private project
 *
 * @copyright Copyright (c) Mathieu Bour
 * @link      https://beminimalist.fr
 */
namespace App\Controller;

use App\Controller\Component\SettingsComponent;
use Cake\Controller\Controller;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;
use DataTables\Controller\Component\DataTablesComponent;

/**
 * Application Controller
 *
 * @property SettingsComponent $Settings
 * @property DataTablesComponent $DataTables
 */
class AppController extends Controller
{
    /**
     * @var array the page helpers; all loaded by default
     */
    public $helpers = [
        'Html'       => [
            'className' => 'Bootstrap.BootstrapHtml'
        ],
        'Form'       => [
            'className' => 'Bootstrap.BootstrapForm'
        ],
        'Paginator'  => [
            'className' => 'Bootstrap.BootstrapPaginator'
        ],
        'Modal'      => [
            'className' => 'Bootstrap.BootstrapModal'
        ],
        'Barcodes',
        'DataTables' => [
            'className' => 'DataTables.DataTables'
        ]
    ];

    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('Security');`
     *
     * @return void
     */
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Settings');
        $this->loadComponent('DataTables.DataTables');

        $this->set('settings', $this->Settings);
    }

    public function beforeFilter(Event $event)
    {

        $this->Perms = TableRegistry::get('Perms');
        $perms = $this->paginate($this->Perms);

        $this->set(compact('perms'));
        $this->set('_serialize', ['perms']);
        $this->set([
            'session' => $this->request->session()
        ]);

        return parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    /**
     * Before render callback.
     *
     * @param \Cake\Event\Event $event The beforeRender event.
     * @return \Cake\Network\Response|null|void
     */
    public function beforeRender(Event $event)
    {
        if (!array_key_exists('_serialize', $this->viewVars) && in_array($this->response->type(), [
                'application/json',
                'application/xml'
            ])
        ) {
            $this->set('_serialize', true);
        }
    }

    /**
     * Get a view var (return null if the viewVar does not exist)
     * @param string $key the viewVar key
     * @return mixed
     */
    public function get(string $key): mixed
    {
        if (!empty($this->viewVars[$key])) {
            return $this->viewVars[$key];
        } else {
            return null;
        }
    }

    /**
     * Set the page title (accessible in viewVars)
     * @param string $title the page title
     * @return void
     */
    public function setTitle(string $title): void
    {
        $this->set(compact('title'));
    }
}
